### ISSUE TITLE
install errors on windows

### ISSUE THREAD

**Issue by belveder79** [tombulled/python-yatwin#1]
Hi,
can you give me some info about the python versions you are using? I tried to get it to work on my Win10 x64 native installing python 2.7 and 3.9, and also using python 2 and 3 in cygwin without luck (the installation always got stuck at a certain point).

Actually I wanted to get it running on Unix or Mac, but it seems to heavily use Windows specific libraries...
Best

**Comment by tombulled** [comment]
Hi @belveder79, apologies for the late reply to this. This library was developed using Python 3 (I don't remember which version specifically, however it was likely an early version such as 3.4) on Windows 10. Unfortunately I am no longer maintaining this library. All the best, Tom
